# Use `allow` to specify which dependencies to maintain

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: ""
    schedule:
      interval: daily
    labels:
    - "automerge"
